apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-app-pod
  template:
    metadata:
      labels:
        app: database-app-pod
    spec:
      containers:
        - name: database-app-container
          image: data:base
          ports:
            - containerPort: 8003
          imagePullPolicy: Never
          resources:
            limits:
              memory: "350Mi"
              cpu: "128m"
            requests:
              memory: "200Mi"
              cpu: "80m"