apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    app.kubernetes.io/name: frontend-app
    app.kubernetes.io/instance: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend-app
      app.kubernetes.io/instance: frontend-deploy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend-app
        app.kubernetes.io/instance: frontend-deploy
    spec:
      containers:
        - name: frontend-app
          image: dashboard:frontend
          resources:
            requests:
              memory: "64Mi" # 64 MebiBytes = 67.1089 Megabytes
              cpu: "250m"
            limits:
              memory: "300Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000