apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app.kubernetes.io/name: frontend-app
    app.kubernetes.io/instance: frontend-deploy
spec:
  selector:
    app.kubernetes.io/name: frontend-app
    app.kubernetes.io/instance: frontend-deploy
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort
