apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app-pod
  template:
    metadata:
      labels:
        app: frontend-app-pod
    spec:
      containers:
        - name: frontend-app-container
          image: dashboard:frontend
          ports:
            - containerPort: 3000
          imagePullPolicy: Never
          resources:
            limits:
              memory: "350Mi"
              cpu: "128m"
            requests:
              memory: "200Mi"
              cpu: "80m"