apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app-pod
  template:
    metadata:
      labels:
        app: frontend-app-pod
    spec:
      containers:
        - name: frontend-app-container
          image: dashboard:frontend
          ports:
            - containerPort: 3000
          imagePullPolicy: Never
          resources:
            limits:
              memory: "512Mi"      # Increased from 350Mi
              cpu: "500m"          # Increased from 128m
            requests:
              memory: "256Mi"      # Increased from 200Mi
              cpu: "250m"          # Increased from 80m
