apiVersion: apps/v1
kind: Deployment
metadata:
  name: head-count-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: head-counting-app-pod
  template:
    metadata:
      labels:
        app: head-counting-app-pod
    spec:
      containers:
        - name: head-counting-app-container
          image: head-counting-service:counter
          ports:
            - containerPort: 8002
          imagePullPolicy: Never