apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: head-count-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: head-count-deploy
  minReplicas: 3
  maxReplicas: 30
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleUp:
      policies:
        - type: Pods
          value: 5
          periodSeconds: 30
        - type: Percent
          value: 50
          periodSeconds: 30
      stabilizationWindowSeconds: 30
    scaleDown:
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
      stabilizationWindowSeconds: 30
