apiVersion: apps/v1
kind: Deployment
metadata:
  name: head-count-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: head-counting-app-pod
  template:
    metadata:
      labels:
        app: head-counting-app-pod
    spec:
      containers:
        - name: head-counting-app-container
          image: head-counting-service:counter
          ports:
            - containerPort: 8002
          imagePullPolicy: Never
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
