apiVersion: apps/v1
kind: Deployment
metadata:
  name: specific-head-count-deploy
  labels:
    app.kubernetes.io/name: specific-head-count-app
    app.kubernetes.io/instance: specific-head-count-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: specific-head-count-app
      app.kubernetes.io/instance: specific-head-count-deploy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: specific-head-count-app
        app.kubernetes.io/instance: specific-head-count-deploy
    spec:
      containers:
        - name: specific-head-count-app
          image: specific-head-count:specific
          resources:
            requests:
              memory: "64Mi" # 64 MebiBytes = 67.1089 Megabytes
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8004