apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-upload-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-upload-app-pod
  template:
    metadata:
      labels:
        app: image-upload-app-pod
    spec:
      containers:
        - name: image-upload-app-container
          image: image-upload-service:upload
          ports:
            - containerPort: 8001
          imagePullPolicy: Never
          resources:
            limits:
              memory: "350Mi"
              cpu: "128m"
            requests:
              memory: "200Mi"
              cpu: "80m"
