apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-upload-deploy
  labels:
    app.kubernetes.io/name: image-upload-app
    app.kubernetes.io/instance: image-upload-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: image-upload-app
      app.kubernetes.io/instance: image-upload-deploy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: image-upload-app
        app.kubernetes.io/instance: image-upload-deploy
    spec:
      containers:
        - name: image-upload-app
          image: image-upload-service:upload
          resources:
            requests:
              memory: "64Mi" # 64 MebiBytes = 67.1089 Megabytes
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8001
